= jeoip

*Discontinued* - MaxMind changed the data format and they provide
their own "free" Java API (registration required).
Please use https://github.com/maxmine/GeoIP2-java.

If somebody figures out the format of the GeoIP2 data without looking
at their source code, I might accept a pull request for updating the code.

== Legacy Information

This code gives access to the GeoIP free database of IP-to-country geolocation data.

It is free software, under the BSD 2-clause license.

See also: http://dev.maxmind.com/geoip/

== Running

Before you can run the tests or the library, you must have the GeoIP Country database installed.
On OpenBSD you can satisfy this requirement by installing the GeoIP data package, i.e., 

	doas pkg_add geolite-country

On other systems you'll have to install `GeoIP.dat` in `/usr/local/share/examples/GeoIP/GeoIP.dat`,
or in some other directory that is pointed to by the environment variable `GEOIP_DIR`.

== Notice

This product uses GeoLite data created by MaxMind, available from http://www.maxmind.com .

