#!/bin/sh

set -x

DIR=$ws/darwinsysweb/WebContent/freeware/
DIST=jeoip-0.3.tar.gz
cp ${DIST} ${DIR}

cd ${DIR}

webinst ${DIST}

cp ${DIST} /usr/ports/distfiles/

cd /usr/ports/mystuff/geo/jeoip

make makesum

sudo make clean

sudo make clean=package 

sudo make package
