package jeoip;

/** Country names and ISO country codes, supplemented by
 * and in correct order for GeoIP database use.
 * @author ian
 */
public class Countries {
	
	public static Country getCountry(int n) {
		if (n < 0 || n > list.length) {
			return null;
		}
		return list[n];
	}

	public static final Country[] list = {
		new Country("--","--","--","--"),
		new Country("Asia/Pacific Region","AP","AP","AS"),
		new Country("Europe","EU","EU","EU"),
		new Country("Andorra","AD","AND","EU"),
		new Country("United Arab Emirates","AE","ARE","AS"),
		new Country("Afghanistan","AF","AFG","AS"),
		new Country("Antigua and Barbuda","AG","ATG","SA"),
		new Country("Anguilla","AI","AIA","SA"),
		new Country("Albania","AL","ALB","EU"),
		new Country("Armenia","AM","ARM","AS"),
		new Country("Netherlands Antilles","AN","ANT","SA"),
		new Country("Angola","AO","AGO","AF"),
		new Country("Antarctica","AQ","AQ","AN"),
		new Country("Argentina","AR","ARG","SA"),
		new Country("American Samoa","AS","ASM","OC"),
		new Country("Austria","AT","AUT","EU"),
		new Country("Australia","AU","AUS","OC"),
		new Country("Aruba","AW","ABW","SA"),
		new Country("Azerbaijan","AZ","AZE","AS"),
		new Country("Bosnia and Herzegovina","BA","BIH","EU"),
		new Country("Barbados","BB","BRB","SA"),
		new Country("Bangladesh","BD","BGD","AS"),
		new Country("Belgium","BE","BEL","EU"),
		new Country("Burkina Faso","BF","BFA","AF"),
		new Country("Bulgaria","BG","BGR","EU"),
		new Country("Bahrain","BH","BHR","AS"),
		new Country("Burundi","BI","BDI","AF"),
		new Country("Benin","BJ","BEN","AF"),
		new Country("Bermuda","BM","BMU","SA"),
		new Country("Brunei Darussalam","BN","BRN","AS"),
		new Country("Bolivia","BO","BOL","SA"),
		new Country("Brazil","BR","BRA","SA"),
		new Country("Bahamas","BS","BHS","SA"),
		new Country("Bhutan","BT","BTN","AS"),
		new Country("Bouvet Island","BV","BV","AF"),
		new Country("Botswana","BW","BWA","AF"),
		new Country("Belarus","BY","BLR","EU"),
		new Country("Belize","BZ","BLZ","SA"),
		new Country("Canada","CA","CAN","NA"),
		new Country("Cocos (Keeling) Islands","CC","CC","AS"),
		new Country("Congo, The Democratic Republic of the","CD","COD","AF"),
		new Country("Central African Republic","CF","CAF","AF"),
		new Country("Congo","CG","COG","AF"),
		new Country("Switzerland","CH","CHE","EU"),
		new Country("Cote D'Ivoire","CI","CIV","AF"),
		new Country("Cook Islands","CK","COK","OC"),
		new Country("Chile","CL","CHL","SA"),
		new Country("Cameroon","CM","CMR","AF"),
		new Country("China","CN","CHN","AS"),
		new Country("Colombia","CO","COL","SA"),
		new Country("Costa Rica","CR","CRI","SA"),
		new Country("Cuba","CU","CUB","SA"),
		new Country("Cape Verde","CV","CPV","AF"),
		new Country("Christmas Island","CX","CX","AS"),
		new Country("Cyprus","CY","CYP","AS"),
		new Country("Czech Republic","CZ","CZE","EU"),
		new Country("Germany","DE","DEU","EU"),
		new Country("Djibouti","DJ","DJI","AF"),
		new Country("Denmark","DK","DNK","EU"),
		new Country("Dominica","DM","DMA","SA"),
		new Country("Dominican Republic","DO","DOM","SA"),
		new Country("Algeria","DZ","DZA","AF"),
		new Country("Ecuador","EC","ECU","SA"),
		new Country("Estonia","EE","EST","EU"),
		new Country("Egypt","EG","EGY","AF"),
		new Country("Western Sahara","EH","ESH","AF"),
		new Country("Eritrea","ER","ERI","AF"),
		new Country("Spain","ES","ESP","EU"),
		new Country("Ethiopia","ET","ETH","AF"),
		new Country("Finland","FI","FIN","EU"),
		new Country("Fiji","FJ","FJI","OC"),
		new Country("Falkland Islands (Malvinas)","FK","FLK","SA"),
		new Country("Micronesia, Federated States of","FM","FSM","OC"),
		new Country("Faroe Islands","FO","FRO","EU"),
		new Country("France","FR","FRA","EU"),
		new Country("France, Metropolitan","FX","FX","EU"),
		new Country("Gabon","GA","GAB","AF"),
		new Country("United Kingdom","GB","GBR","EU"),
		new Country("Grenada","GD","GRD","SA"),
		new Country("Georgia","GE","GEO","AS"),
		new Country("French Guiana","GF","GUF","SA"),
		new Country("Ghana","GH","GHA","AF"),
		new Country("Gibraltar","GI","GIB","EU"),
		new Country("Greenland","GL","GRL","SA"),
		new Country("Gambia","GM","GMB","AF"),
		new Country("Guinea","GN","GIN","AF"),
		new Country("Guadeloupe","GP","GLP","SA"),
		new Country("Equatorial Guinea","GQ","GNQ","AF"),
		new Country("Greece","GR","GRC","EU"),
		new Country("South Georgia and the South Sandwich Islands","GS","GS","SA"),
		new Country("Guatemala","GT","GTM","SA"),
		new Country("Guam","GU","GUM","OC"),
		new Country("Guinea-Bissau","GW","GNB","AF"),
		new Country("Guyana","GY","GUY","SA"),
		new Country("Hong Kong","HK","HKG","AS"),
		new Country("Heard Island and McDonald Islands","HM","HM","AF"),
		new Country("Honduras","HN","HND","SA"),
		new Country("Croatia","HR","HRV","EU"),
		new Country("Haiti","HT","HTI","SA"),
		new Country("Hungary","HU","HUN","EU"),
		new Country("Indonesia","ID","IDN","AS"),
		new Country("Ireland","IE","IRL","EU"),
		new Country("Israel","IL","ISR","AS"),
		new Country("India","IN","IND","AS"),
		new Country("British Indian Ocean Territory","IO","IO","AS"),
		new Country("Iraq","IQ","IRQ","AS"),
		new Country("Iran, Islamic Republic of","IR","IRN","AS"),
		new Country("Iceland","IS","ISL","EU"),
		new Country("Italy","IT","ITA","EU"),
		new Country("Jamaica","JM","JAM","SA"),
		new Country("Jordan","JO","JOR","AS"),
		new Country("Japan","JP","JPN","AS"),
		new Country("Kenya","KE","KEN","AF"),
		new Country("Kyrgyzstan","KG","KGZ","AS"),
		new Country("Cambodia","KH","KHM","AS"),
		new Country("Kiribati","KI","KIR","OC"),
		new Country("Comoros","KM","COM","AF"),
		new Country("Saint Kitts and Nevis","KN","KNA","SA"),
		new Country("Korea, Democratic People's Republic of","KP","PRK","AS"),
		new Country("Korea, Republic of","KR","KOR","AS"),
		new Country("Kuwait","KW","KWT","AS"),
		new Country("Cayman Islands","KY","CYM","SA"),
		new Country("Kazakhstan","KZ","KAZ","AS"),
		new Country("Lao People's Democratic Republic","LA","LAO","AS"),
		new Country("Lebanon","LB","LBN","AS"),
		new Country("Saint Lucia","LC","LCA","SA"),
		new Country("Liechtenstein","LI","LIE","EU"),
		new Country("Sri Lanka","LK","LKA","AS"),
		new Country("Liberia","LR","LBR","AF"),
		new Country("Lesotho","LS","LSO","AF"),
		new Country("Lithuania","LT","LTU","EU"),
		new Country("Luxembourg","LU","LUX","EU"),
		new Country("Latvia","LV","LVA","EU"),
		new Country("Libyan Arab Jamahiriya","LY","LBY","AF"),
		new Country("Morocco","MA","MAR","AF"),
		new Country("Monaco","MC","MCO","EU"),
		new Country("Moldova, Republic of","MD","MDA","EU"),
		new Country("Madagascar","MG","MDG","AF"),
		new Country("Marshall Islands","MH","MHL","OC"),
		new Country("Macedonia","MK","MKD","EU"),
		new Country("Mali","ML","MLI","AF"),
		new Country("Myanmar","MM","MMR","AS"),
		new Country("Mongolia","MN","MNG","AS"),
		new Country("Macau","MO","MAC","AS"),
		new Country("Northern Mariana Islands","MP","MNP","OC"),
		new Country("Martinique","MQ","MTQ","SA"),
		new Country("Mauritania","MR","MRT","AF"),
		new Country("Montserrat","MS","MSR","SA"),
		new Country("Malta","MT","MLT","EU"),
		new Country("Mauritius","MU","MUS","AF"),
		new Country("Maldives","MV","MDV","AS"),
		new Country("Malawi","MW","MWI","AF"),
		new Country("Mexico","MX","MEX","NA"),
		new Country("Malaysia","MY","MYS","AS"),
		new Country("Mozambique","MZ","MOZ","AF"),
		new Country("Namibia","NA","NAM","AF"),
		new Country("New Caledonia","NC","NCL","OC"),
		new Country("Niger","NE","NER","AF"),
		new Country("Norfolk Island","NF","NFK","OC"),
		new Country("Nigeria","NG","NGA","AF"),
		new Country("Nicaragua","NI","NIC","SA"),
		new Country("Netherlands","NL","NLD","EU"),
		new Country("Norway","NO","NOR","EU"),
		new Country("Nepal","NP","NPL","AS"),
		new Country("Nauru","NR","NRU","OC"),
		new Country("Niue","NU","NIU","OC"),
		new Country("New Zealand","NZ","NZL","OC"),
		new Country("Oman","OM","OMN","AS"),
		new Country("Panama","PA","PAN","SA"),
		new Country("Peru","PE","PER","SA"),
		new Country("French Polynesia","PF","PYF","OC"),
		new Country("Papua New Guinea","PG","PNG","OC"),
		new Country("Philippines","PH","PHL","AS"),
		new Country("Pakistan","PK","PAK","AS"),
		new Country("Poland","PL","POL","EU"),
		new Country("Saint Pierre and Miquelon","PM","SPM","SA"),
		new Country("Pitcairn Islands","PN","PCN","OC"),
		new Country("Puerto Rico","PR","PRI","SA"),
		new Country("Palestinian Territory, Occupied","PS","PSE","AS"),
		new Country("Portugal","PT","PRT","EU"),
		new Country("Palau","PW","PLW","OC"),
		new Country("Paraguay","PY","PRY","SA"),
		new Country("Qatar","QA","QAT","AS"),
		new Country("Reunion","RE","REU","AF"),
		new Country("Romania","RO","ROU","EU"),
		new Country("Russian Federation","RU","RUS","AS"),
		new Country("Rwanda","RW","RWA","AF"),
		new Country("Saudi Arabia","SA","SAU","AS"),
		new Country("Solomon Islands","SB","SLB","OC"),
		new Country("Seychelles","SC","SYC","AF"),
		new Country("Sudan","SD","SDN","AF"),
		new Country("Sweden","SE","SWE","EU"),
		new Country("Singapore","SG","SGP","AS"),
		new Country("Saint Helena","SH","SHN","AF"),
		new Country("Slovenia","SI","SVN","EU"),
		new Country("Svalbard and Jan Mayen","SJ","SJM","EU"),
		new Country("Slovakia","SK","SVK","EU"),
		new Country("Sierra Leone","SL","SLE","AF"),
		new Country("San Marino","SM","SMR","EU"),
		new Country("Senegal","SN","SEN","AF"),
		new Country("Somalia","SO","SOM","AF"),
		new Country("Suriname","SR","SUR","SA"),
		new Country("Sao Tome and Principe","ST","STP","AF"),
		new Country("El Salvador","SV","SLV","SA"),
		new Country("Syrian Arab Republic","SY","SYR","AS"),
		new Country("Swaziland","SZ","SWZ","AF"),
		new Country("Turks and Caicos Islands","TC","TCA","SA"),
		new Country("Chad","TD","TCD","AF"),
		new Country("French Southern Territories","TF","TF","AF"),
		new Country("Togo","TG","TGO","AF"),
		new Country("Thailand","TH","THA","AS"),
		new Country("Tajikistan","TJ","TJK","AS"),
		new Country("Tokelau","TK","TKL","OC"),
		new Country("Turkmenistan","TM","TLS","AS"),
		new Country("Tunisia","TN","TKM","AF"),
		new Country("Tonga","TO","TUN","OC"),
		new Country("East Timor","TP","TON","AS"),
		new Country("Turkey","TR","TUR","AS"),
		new Country("Trinidad and Tobago","TT","TTO","SA"),
		new Country("Tuvalu","TV","TUV","OC"),
		new Country("Taiwan","TW","TWN","AS"),
		new Country("Tanzania, United Republic of","TZ","TZA","AF"),
		new Country("Ukraine","UA","UKR","EU"),
		new Country("Uganda","UG","UGA","AF"),
		new Country("United States Minor Outlying Islands","UM","UM","OC"),
		new Country("United States","US","USA","NA"),
		new Country("Uruguay","UY","URY","SA"),
		new Country("Uzbekistan","UZ","UZB","AS"),
		new Country("Holy See (Vatican City State)","VA","VAT","EU"),
		new Country("Saint Vincent and the Grenadines","VC","VCT","SA"),
		new Country("Venezuela","VE","VEN","SA"),
		new Country("Virgin Islands, British","VG","VGB","SA"),
		new Country("Virgin Islands, U.S.","VI","VIR","SA"),
		new Country("Vietnam","VN","VNM","AS"),
		new Country("Vanuatu","VU","VUT","OC"),
		new Country("Wallis and Futuna","WF","WLF","OC"),
		new Country("Samoa","WS","WSM","OC"),
		new Country("Yemen","YE","YEM","AS"),
		new Country("Mayotte","YT","YT","AF"),
		new Country("Yugoslavia","YU","YUG","EU"),
		new Country("South Africa","ZA","ZAF","AF"),
		new Country("Zambia","ZM","ZMB","AF"),
		new Country("Zaire","ZR","ZR","AF"),
		new Country("Zimbabwe","ZW","ZWE","AF"),
		new Country("Anonymous Proxy","A1","A1","--"),
		new Country("Satellite Provider","A2","A2","--"),
		new Country("Other","O1","O1","--")
	};
}
